defaults:
  - _self_
  # compression config
  - compress: wanda

base_model: meta-llama/Llama-2-7b-hf
seqlen: -1 # -1 means native seqlen
verbose: False
run_name: test_compress


#dataset level config
calibration_data_type: hessian_diag
dataset_config_base_path: config/dataset/
datasets:
  - dataset_config: c4_multilingual
    n_samples: 96 
    ctx_len: 4096
  - dataset_config: codeparrot
    n_samples: 32 
    ctx_len: 4096
  


#paths to the various files
data_dir: /data/lliu/LLM_data
weight_path: ${data_dir}/${base_model}/original_weights
calibration_data_path: ${data_dir}/${base_model}/${calibration_data_type}
save_path: ./models/${base_model}/compressed/${run_name}
temp_path: ./models/${base_model}/temp/${run_name}

batch_size: 4
seed: 0
add_bias: False
offload_activations: False
resume: False
resume_layerwise: False
push_to_hub: False
log_wandb: False
create_non_compressed_model: False #whether we are creating a non-compressed model with the same weights for evaluation
#sweep for ablation tests
iter_sweep: False #whether we are doing a sweep over iterations
iter_sweep_freq: 1000 #frequency of saving the model during iteration sweep