seed: 0
base_model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
verbose: True

# Dataset level config
dataset_config_base_path: config/dataset/
datasets:
  - dataset_config: gsm8k
    n_samples: 128
    ctx_len: 1024

# Output directory
output_dir: ./data/qa_datasets_with_answers

# Generation parameters
generation:
  max_new_tokens: 512
  do_sample: False
  temperature: 0.7
  top_p: 0.9