method: Sparse
kwargs:
  frac_sparse: 0.5
  sparse_types:
  - unstructured
  sparse_criterions:
  - wanda
  pattern:
  - 2
  - 4
  normalizer_kwargs:
    norm_order:
    - 0
    - 1
    zero:
    - false
    - false
    p: 2
  stochastic: False