init_config:
  _target_: "src.sparse_compress.SparseLinear"

compression_config:
  frac_nonzero: 0.5
  sparse_group: "d_in" # use "d_in" to set the sparse group to the input dimension
  normalizer_kwargs:
    norm_order: []
    zero:
    - false
    - false
    p: 2