lm_eval_tasks:
  # - task: gpqa
  #   num_fewshot: 0
  # - task: leaderboard_bbh
  #   num_fewshot: 3
  - task: leaderboard_gpqa
    num_fewshot: 0
  # - task: leaderboard_ifeval
  #   num_fewshot: 0
  # - task: leaderboard_math_hard
  #   num_fewshot: 4
  # - task: leaderboard_mmlu_pro
  #   num_fewshot: 5
  # - task: leaderboard_musr
  #   num_fewshot: 0
